#############################################################################
# Generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#  Nov 26, 2025 08:28:57 PM EET  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


#######  Default Fonts ########
set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkTooltipFont
set vTcl(actual_gui_font_tooltip_name)  TkTooltipFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #dadded
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) Absolute
set vTcl(mode) Absolute
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base

############ toplevel.wgt #############################
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -borderwidth 0 -relief flat -background #d9d9d9 -container 0 \
        -height 0 -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 0 -padx 0 -pady 0 -takefocus 0 -width 0 
    wm focusmodel $top passive
    wm geometry $top 471x301+697+167
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1926 964
    wm minsize $top 117 2
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    set toptitle "Users iteractions"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "root" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    labelframe "$top.lab51" \
        -borderwidth 2 -font "TkDefaultFont" -foreground #000000 \
        -labelanchor nw -relief groove -text "Actions" -background #d9d9d9 \
        -container 0 -height 275 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -padx 0 -pady 0 \
        -takefocus 0 -width 190 
    vTcl:DefineAlias "$top.lab51" "Actionsframe" vTcl:WidgetProc "root" 1
    set site_3_0 $top.lab51
    entry "$site_3_0.ent52" \
        -background #ffffff -borderwidth 1 -cursor xterm \
        -disabledbackground SystemButtonFace -disabledforeground #a3a3a3 \
        -exportselection 0 -font "TkFixedFont" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 0 -insertbackground #000000 -insertborderwidth 0 \
        -insertofftime 300 -insertontime 600 -insertwidth 2 -justify left \
        -readonlybackground SystemButtonFace -relief sunken \
        -selectbackground #d9d9d9 -selectborderwidth 0 \
        -selectforeground black -state normal -validate none -width 144 
    vTcl:DefineAlias "$site_3_0.ent52" "username" vTcl:WidgetProc "root" 1
    label "$site_3_0.lab55" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground #000000 \
        -height 0 -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 0 -justify center -padx 1 -pady 1 -relief flat \
        -state normal -takefocus 0 -text "User name" -underline -1 -width 0 \
        -wraplength 0 
    vTcl:DefineAlias "$site_3_0.lab55" "user_lbl" vTcl:WidgetProc "root" 1
    label "$site_3_0.lab56" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground #000000 \
        -height 0 -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 0 -justify center -padx 1 -pady 1 -relief flat \
        -state normal -takefocus 0 -text "Passowrd" -underline -1 -width 0 \
        -wraplength 0 
    vTcl:DefineAlias "$site_3_0.lab56" "pass_lbl" vTcl:WidgetProc "root" 1
    label "$site_3_0.lab57" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground #000000 \
        -height 0 -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 0 -justify center -padx 1 -pady 1 -relief flat \
        -state normal -takefocus 0 -text "Re-enter password" -underline -1 \
        -width 0 -wraplength 0 
    vTcl:DefineAlias "$site_3_0.ent54" "repassword" vTcl:WidgetProc "root" 1
    entry "$site_3_0.ent53" \
        -background #ffffff -borderwidth 1 -cursor xterm \
        -disabledbackground SystemButtonFace -disabledforeground #a3a3a3 \
        -exportselection 0 -font "TkFixedFont" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 0 -insertbackground #000000 -insertborderwidth 0 \
        -insertofftime 300 -insertontime 600 -insertwidth 2 -justify left \
        -readonlybackground SystemButtonFace -relief sunken \
        -selectbackground #d9d9d9 -selectborderwidth 0 \
        -selectforeground black -show * -state normal -validate none \
        -width 144 
    vTcl:DefineAlias "$site_3_0.lab57" "repass_lbl" vTcl:WidgetProc "root" 1
    entry "$site_3_0.ent54" \
        -background #ffffff -borderwidth 1 -cursor xterm \
        -disabledbackground SystemButtonFace -disabledforeground #a3a3a3 \
        -exportselection 0 -font "TkFixedFont" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 0 -insertbackground #000000 -insertborderwidth 0 \
        -insertofftime 300 -insertontime 600 -insertwidth 2 -justify left \
        -readonlybackground SystemButtonFace -relief sunken \
        -selectbackground #d9d9d9 -selectborderwidth 0 \
        -selectforeground black -show * -state normal -validate none \
        -width 144 
    vTcl:DefineAlias "$site_3_0.ent53" "password" vTcl:WidgetProc "root" 1
    ttk::button "$site_3_0.tBu58" \
        -command "addUser" -default normal -takefocus ttk::takefocus \
        -text "Add user" -underline -1 -width 145 -compound left \
        -state disabled -style "" 
    vTcl:DefineAlias "$site_3_0.tBu58" "add_btn" vTcl:WidgetProc "root" 1
    ttk::button "$site_3_0.tBu59" \
        -command "updateUser" -default normal -takefocus ttk::takefocus \
        -text "Update user" -underline -1 -width 145 -compound left \
        -state disabled -style "" 
    vTcl:DefineAlias "$site_3_0.tBu59" "upd_btn" vTcl:WidgetProc "root" 1
    ttk::button "$site_3_0.tBu60" \
        -command "deleteUser" -default normal -takefocus ttk::takefocus \
        -text "Delete user" -underline -1 -width 145 -compound left \
        -state disabled -style "" 
    vTcl:DefineAlias "$site_3_0.tBu60" "del_btn" vTcl:WidgetProc "root" 1
# add p1 basename = $site_3_0.ent52
    place $site_3_0.ent52 \
        -in $site_3_0 -x 20 -y 50 -width 144 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $site_3_0.lab55
    place $site_3_0.lab55 \
        -in $site_3_0 -x 20 -y 30 -anchor nw -bordermode ignore 
# add p1 basename = $site_3_0.lab56
    place $site_3_0.lab56 \
        -in $site_3_0 -x 20 -y 80 -anchor nw -bordermode ignore 
# add p1 basename = $site_3_0.lab57
    place $site_3_0.lab57 \
        -in $site_3_0 -x 20 -y 130 -anchor nw -bordermode ignore 
# add p1 basename = $site_3_0.ent54
    place $site_3_0.ent54 \
        -in $site_3_0 -x 20 -y 150 -width 144 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $site_3_0.ent53
    place $site_3_0.ent53 \
        -in $site_3_0 -x 20 -y 100 -width 144 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $site_3_0.tBu58
    place $site_3_0.tBu58 \
        -in $site_3_0 -x 20 -y 180 -width 145 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $site_3_0.tBu59
    place $site_3_0.tBu59 \
        -in $site_3_0 -x 20 -y 210 -width 145 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $site_3_0.tBu60
    place $site_3_0.tBu60 \
        -in $site_3_0 -x 20 -y 240 -width 145 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe "$top.lab49" \
        -borderwidth 2 -font "TkDefaultFont" -foreground #000000 \
        -labelanchor nw -relief groove -text "Existing users" \
        -background #d9d9d9 -container 0 -height 275 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 0 -padx 0 -pady 0 -takefocus 0 -width 250 
    vTcl:DefineAlias "$top.lab49" "Usersframe1" vTcl:WidgetProc "root" 1
    set site_3_0 $top.lab49
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd "$site_3_0.scr61" \
        -borderwidth 0 -relief flat -background #d9d9d9 -container 0 \
        -height 75 -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 0 -padx 0 -pady 0 -takefocus 0 -width 125 
    vTcl:DefineAlias "$site_3_0.scr61" "users_list" vTcl:WidgetProc "root" 1

    $site_3_0.scr61.01 configure -background white \
        -cursor xterm \
        -disabledforeground #a3a3a3 \
        -exportselection 0 \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground #d9d9d9 \
        -selectforeground black \
        -width 10
# add p1 basename = $site_3_0.scr61
    place $site_3_0.scr61 \
        -in $site_3_0 -x 10 -y 20 -width 231 -relwidth 0 -height 242 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
# add p1 basename = $top.lab51
    place $top.lab51 \
        -in $top -x 270 -y 10 -width 190 -relwidth 0 -height 275 -relheight 0 \
        -anchor nw -bordermode ignore 
# add p1 basename = $top.lab49
    place $top.lab49 \
        -in $top -x 10 -y 10 -width 250 -relwidth 0 -height 275 -relheight 0 \
        -anchor nw -bordermode ignore 

############# Spot ttt ##############################

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

