#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Nov 26, 2025 08:28:57 PM EET  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os

_location = os.path.dirname(__file__)

import user_gui_support

os.chdir("..")

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'black' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = '#dadded' 

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran: return        
    try: user_gui_support.root.tk.call('source',
                os.path.join(_location, 'themes', 'default.tcl'))
    except: pass
    style = ttk.Style()
    style.theme_use('default')
    style.configure('.', font = "TkDefaultFont")
    if sys.platform == "win32":
       style.theme_use('winnative')    
    _style_code_ran = 1

class tk_app:
    def updateList(self):
        self.users_list.delete(0,tk.END)
        self.users_list.insert(1, "__Add user__")
        users = user_gui_support.execSQL('SELECT `NAME` from `users_tbl`;')
        i = 2
        for u in users:
            self.users_list.insert(i, u[0])
            i+=1
        self.top.update()
    
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("471x301+697+167")
        top.minsize(117, 2)
        top.maxsize(1926, 964)
        top.resizable(0,  0)
        top.title("Users iteractions")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top

        self.Actionsframe = tk.LabelFrame(self.top)
        self.Actionsframe.place(x=270, y=10, height=275, width=190)
        self.Actionsframe.configure(relief='groove')
        self.Actionsframe.configure(foreground="#000000")
        self.Actionsframe.configure(text='''Actions''')
        self.Actionsframe.configure(background="#d9d9d9")
        self.Actionsframe.configure(highlightbackground="#d9d9d9")
        self.Actionsframe.configure(highlightcolor="#000000")

        self.username = tk.Entry(self.Actionsframe)
        self.username.place(x=20, y=50, height=19, width=144
                , bordermode='ignore')
        self.username.configure(background="#ffffff")
        self.username.configure(disabledforeground="#a3a3a3")
        self.username.configure(exportselection="0")
        self.username.configure(font="TkFixedFont")
        self.username.configure(foreground="#000000")
        self.username.configure(highlightbackground="#d9d9d9")
        self.username.configure(highlightcolor="#000000")
        self.username.configure(insertbackground="#000000")
        self.username.configure(selectbackground="#d9d9d9")
        self.username.configure(selectforeground="black")
        self.username.configure(state='readonly')

        self.user_lbl = tk.Label(self.Actionsframe)
        self.user_lbl.place(x=20, y=30, height=19, width=69, bordermode='ignore')

        self.user_lbl.configure(activebackground="#d9d9d9")
        self.user_lbl.configure(activeforeground="black")
        self.user_lbl.configure(anchor='w')
        self.user_lbl.configure(background="#d9d9d9")
        self.user_lbl.configure(compound='left')
        self.user_lbl.configure(disabledforeground="#a3a3a3")
        self.user_lbl.configure(foreground="#000000")
        self.user_lbl.configure(highlightbackground="#d9d9d9")
        self.user_lbl.configure(highlightcolor="#000000")
        self.user_lbl.configure(text='''User name:''')

        self.pass_lbl = tk.Label(self.Actionsframe)
        self.pass_lbl.place(x=20, y=80, height=19, width=62, bordermode='ignore')

        self.pass_lbl.configure(activebackground="#d9d9d9")
        self.pass_lbl.configure(activeforeground="black")
        self.pass_lbl.configure(anchor='w')
        self.pass_lbl.configure(background="#d9d9d9")
        self.pass_lbl.configure(compound='left')
        self.pass_lbl.configure(disabledforeground="#a3a3a3")
        self.pass_lbl.configure(foreground="#000000")
        self.pass_lbl.configure(highlightbackground="#d9d9d9")
        self.pass_lbl.configure(highlightcolor="#000000")
        self.pass_lbl.configure(text='''Passowrd:''')

        self.repass_lbl = tk.Label(self.Actionsframe)
        self.repass_lbl.place(x=20, y=130, height=19, width=110
                , bordermode='ignore')
        self.repass_lbl.configure(activebackground="#d9d9d9")
        self.repass_lbl.configure(activeforeground="black")
        self.repass_lbl.configure(anchor='w')
        self.repass_lbl.configure(background="#d9d9d9")
        self.repass_lbl.configure(compound='left')
        self.repass_lbl.configure(disabledforeground="#a3a3a3")
        self.repass_lbl.configure(foreground="#000000")
        self.repass_lbl.configure(highlightbackground="#d9d9d9")
        self.repass_lbl.configure(highlightcolor="#000000")
        self.repass_lbl.configure(text='''Re-enter password:''')

        self.password = tk.Entry(self.Actionsframe)
        self.password.place(x=20, y=100, height=19, width=144
                , bordermode='ignore')
        self.password.configure(background="#ffffff")
        self.password.configure(disabledforeground="#a3a3a3")
        self.password.configure(exportselection="0")
        self.password.configure(font="TkFixedFont")
        self.password.configure(foreground="#000000")
        self.password.configure(highlightbackground="#d9d9d9")
        self.password.configure(highlightcolor="#000000")
        self.password.configure(insertbackground="#000000")
        self.password.configure(selectbackground="#d9d9d9")
        self.password.configure(selectforeground="black")
        self.password.configure(show="*")
        self.password.configure(state='readonly')
        
        self.repassword = tk.Entry(self.Actionsframe)
        self.repassword.place(x=20, y=150, height=19, width=144
                , bordermode='ignore')
        self.repassword.configure(background="#ffffff")
        self.repassword.configure(disabledforeground="#a3a3a3")
        self.repassword.configure(exportselection="0")
        self.repassword.configure(font="TkFixedFont")
        self.repassword.configure(foreground="#000000")
        self.repassword.configure(highlightbackground="#d9d9d9")
        self.repassword.configure(highlightcolor="#000000")
        self.repassword.configure(insertbackground="#000000")
        self.repassword.configure(selectbackground="#d9d9d9")
        self.repassword.configure(selectforeground="black")
        self.repassword.configure(show="*")
        self.repassword.configure(state='readonly')

        _style_code()
        self.add_btn = ttk.Button(self.Actionsframe)
        self.add_btn.place(x=20, y=180, height=24, width=145
                , bordermode='ignore')
        self.add_btn.configure(command=user_gui_support.addUser)
        self.add_btn.configure(text='''Add user''')
        self.add_btn.configure(compound='left')
        self.add_btn.configure(state='disabled')

        self.upd_btn = ttk.Button(self.Actionsframe)
        self.upd_btn.place(x=20, y=210, height=24, width=145
                , bordermode='ignore')
        self.upd_btn.configure(command=user_gui_support.updateUser)
        self.upd_btn.configure(text='''Update user''')
        self.upd_btn.configure(compound='left')
        self.upd_btn.configure(state='disabled')

        self.del_btn = ttk.Button(self.Actionsframe)
        self.del_btn.place(x=20, y=240, height=24, width=145
                , bordermode='ignore')
        self.del_btn.configure(command=user_gui_support.deleteUser)
        self.del_btn.configure(text='''Delete user''')
        self.del_btn.configure(compound='left')
        self.del_btn.configure(state='disabled')

        self.Usersframe1 = tk.LabelFrame(self.top)
        self.Usersframe1.place(x=10, y=10, height=275, width=250)
        self.Usersframe1.configure(relief='groove')
        self.Usersframe1.configure(foreground="#000000")
        self.Usersframe1.configure(text='''Existing users''')
        self.Usersframe1.configure(background="#d9d9d9")
        self.Usersframe1.configure(highlightbackground="#d9d9d9")
        self.Usersframe1.configure(highlightcolor="#000000")

        self.users_list = ScrolledListBox(self.Usersframe1)
        self.users_list.place(x=10, y=20, height=242, width=231
                , bordermode='ignore')
        self.users_list.bind("<<ListboxSelect>>", user_gui_support.selectUser)
        self.users_list.configure(background="white")
        self.users_list.configure(cursor="xterm")
        self.users_list.configure(disabledforeground="#a3a3a3")
        self.users_list.configure(exportselection="0")
        self.users_list.configure(font="TkFixedFont")
        self.users_list.configure(foreground="black")
        self.users_list.configure(highlightbackground="#d9d9d9")
        self.users_list.configure(highlightcolor="#d9d9d9")
        self.users_list.configure(selectbackground="#d9d9d9")
        self.users_list.configure(selectforeground="black")
        self.updateList()

        ##self.users_list.select_set(0) #This only sets focus on the first item.
        ##self.users_list.event_generate("<<ListboxSelect>>")

# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''
    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))
        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')
        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)
        # Copy geometry methods of master  (taken from ScrolledText.py)
        methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledListBox(AutoScroll, tk.Listbox):
    '''A standard Tkinter Listbox widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        tk.Listbox.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)
    def size_(self):
        sz = tk.Listbox.size(self)
        return sz

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')

def start_up():
    user_gui_support.main()

if __name__ == '__main__':
    user_gui_support.main()




