BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "users_tbl" (
	"ID"	INTEGER NOT NULL DEFAULT 101 UNIQUE,
	"NAME"	TEXT NOT NULL,
	"PASSWORD"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
COMMIT;
