#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Nov 26, 2025 08:25:55 PM EET  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter import messagebox
from tkinter.constants import *

import sqlite3
import os
import hashlib
import json

import user_gui

_debug = True # False to eliminate debug printing from callback functions.

def addUser():
    if len(_w1.username.get()) == 0:
        tk.messagebox.showerror("showerror", "User name is empty")
        return
    if _w1.password.get() != _w1.repassword.get():
        tk.messagebox.showerror("showerror", "Passwords do not match")
        return
    result = execSQL(f"""SELECT COUNT(`NAME`) FROM `users_tbl` WHERE `NAME`='{_w1.username.get()}';""")
    result = result[0]
    result  = result[0]
    if result != 0:
        tk.messagebox.showerror("showerror", "User exist")
        return
    pbHash = encryptPass(_w1.password.get())
    execSQL(f"INSERT INTO `users_tbl` (`NAME`, `PASSWORD`) VALUES('{_w1.username.get()}', '{pbHash}')")
    _w1.updateList()

def updateUser():
    if _w1.password.get() == '*'*8:
        tk.messagebox.showerror("showerror", "Enter password")
        return    
    if (_w1.password.get() != _w1.repassword.get()):
        tk.messagebox.showerror("showerror", "Passwords do not match")
        return
    pbHash = encryptPass(_w1.password.get())
    execSQL(f"""UPDATE `users_tbl` SET `PASSWORD`='{pbHash}' WHERE `NAME`='{_w1.username.get()}';""")

def deleteUser():
    execSQL(f"""DELETE FROM `users_tbl` WHERE `NAME`='{_w1.username.get()}';""")
    _w1.updateList()

def selectUser(arg):
    global _w1
    SelectList = _w1.users_list.curselection()
    if _w1.users_list.get(SelectList[0]) == "__Add user__":
        _w1.add_btn.configure(state='enable')
        _w1.upd_btn.configure(state='disabled')
        _w1.del_btn.configure(state='disabled')
        _w1.username.configure(state='normal')
        _w1.password.configure(state='normal')
        _w1.repassword.configure(state='normal')
        _w1.username.delete(0,END)
        _w1.password.delete(0,END)
        _w1.repassword.delete(0,END)
    else:
        _w1.username.configure(state='normal')
        _w1.add_btn.configure(state='disabled')
        _w1.upd_btn.configure(state='enable')
        _w1.del_btn.configure(state='enable')
        _w1.password.configure(state='normal')
        _w1.repassword.configure(state='normal')      
        _w1.username.delete(0, END)
        _w1.username.insert(0, _w1.users_list.get(SelectList[0]))
        _w1.password.delete(0, END)
        _w1.password.insert(0, "*"*8)
        _w1.repassword.delete(0, END)
        _w1.repassword.insert(0, "*"*8)
        _w1.username.configure(state='readonly')

def execSQL(sql_query_str):
    #print(sql_query_str)  #DEBUG
    try:
        sqliteConnection = sqlite3.connect(db_name)
        cursor = sqliteConnection.cursor()
        cursor.execute(sql_query_str)
        result = cursor.fetchall()
        cursor.close()
        return result

    except sqlite3.Error as error:
        tk.messagebox.showerror("showerror", 'Error occurred - ' + str(error))

    finally:
        if sqliteConnection:
            sqliteConnection.commit()
            sqliteConnection.close()

def encryptPass(clear_txt_pass):
    hash_object = hashlib.sha1(clear_txt_pass.encode())
    return hash_object.hexdigest()

def initDB():
    if not os.path.exists(db_name):
        try:
            sqliteConnection = sqlite3.connect(db_name)
            cursor = sqliteConnection.cursor()
            cursor.executescript(db_creation_script)
        except sqlite3.Error as error:
            tk.messagebox.showerror("showerror", 'Error occurred - ' + str(error))

        finally:
            if sqliteConnection:
                sqliteConnection.commit()
                sqliteConnection.close()

db_name = 'users_db'

db_creation_script ='''BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "users_tbl" (
	"ID"	INTEGER NOT NULL DEFAULT 101 UNIQUE,
	"NAME"	TEXT NOT NULL,
	"PASSWORD"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
COMMIT;'''

def main(*args):
    '''Main entry point for the application.'''
    with open('config.json', 'r') as file:
        data = json.load(file)
    global db_name
    db_name = data['users_db']
    initDB()
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = user_gui.tk_app(_top1)
    root.mainloop()

if __name__ == '__main__':
    user_gui.start_up()




